title: Intelligent Systems 2018-2
description: Universidad Nacional de Colombia, Bogotá
sitename: Intelligent Systems
baseurl: '/is-2018-2'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
